name: Build Zeal 8-bit OS

on:
  push:
    branches:
      - main
  workflow_dispatch:    


jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout from git
        uses: actions/checkout@v3
        with:
          submodules: 'true' # future use
          fetch-depth: 0

      - name: Install prerequisites
        shell: bash
        run: |
            sudo snap remove z88dk
            sudo snap install --edge z88dk
            sudo snap alias z88dk.z88dk-z80asm z88dk-z80asm
            sudo apt install -y jq make lftp

      - name: Build Zeal 8-bit OS (zeal8bit target)
        shell: bash
        run: |
          wget $CONF_SERVER/roms/config/os.conf
          wget $CONF_SERVER/roms/config/osconfig.asm
          mv osconfig.asm include/
          z88dk-z80asm
          make
          mv build/os_with_romdisk.img build/$(git describe --tags).img
        env:
            CONF_SERVER: ${{ secrets.ZEAL8BIT_CONF_SITE }}

